# Generated by Django 4.0.3 on 2022-04-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='compete',
            new_name='complete',
        ),
    ]
